/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FILES;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class loding extends javax.swing.JFrame {

    /**
     * Creates new form loding
     */
     
   
    public loding() {
        initComponents();
        
       
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lodingbar = new javax.swing.JProgressBar();
        lodevalue = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "WELCOME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Agency FB", 1, 36))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/quiz.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 460, 320));

        lodingbar.setBackground(new java.awt.Color(0, 0, 0,0));
        lodingbar.setFont(new java.awt.Font("Agency FB", 0, 10)); // NOI18N
        lodingbar.setForeground(new java.awt.Color(51, 51, 255));
        lodingbar.setBorder(null);
        lodingbar.setBorderPainted(false);
        jPanel1.add(lodingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 730, 20));

        lodevalue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lodevalue.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(lodevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 50, 30));

        msg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        msg.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 400, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("PLEASE WAIT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-close-36.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 462));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
               
               loding s=new loding();
               s.setVisible(true);
              try{
                   for(int i=0;i<=100;i++){
                       Thread.sleep(60);
                       s.lodevalue.setText(i+"%");
                       if (i<10){
                           s.msg.setText("LODING");
                       }
                       if (i==10){
                           s.msg.setText("CONNECTING DATABASE REQUISTING OPEN XAMPP");
                          try{
                               Process process = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqld.exe");
                          }catch(Exception e)
                          {
                               JOptionPane.showMessageDialog(s,"DATABASE NOT FOUND\n"+e);
                               System.exit(0);
                          }
                       }
                       if (i==40){
                           s.msg.setText("DATABASE CONNECTED");
                       }
                       if (i>70){
                           s.msg.setText("PLEASE WAIT LOADING");
                           
                       }
                       if(i==100){
                           s.dispose();
                           login l = new login();
                           l.setVisible(true);
                       }
                       s.lodingbar.setValue(i);
                       
                   }
               }catch(Exception e){
                   JOptionPane.showMessageDialog(s, e);
               }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lodevalue;
    private javax.swing.JProgressBar lodingbar;
    private javax.swing.JLabel msg;
    // End of variables declaration//GEN-END:variables
}
