
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FILES;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User1
 */
public class NOTIFY extends javax.swing.JFrame {

    /**
     * Creates new form NOTIFY
     */
    private  String ID1;
    private  String NAME1;
    private  String USERNAME1;
    private  String CATEGORY1;
    Connection con ;
    PreparedStatement str;
    ResultSet rs;
    public NOTIFY(String i,String n,String un) {
        this.ID1=i;
        this.NAME1=n;
        this.USERNAME1 =un;
        initComponents();
        strtbtn.hide();
       con= new ConnectDB().Connect();
       getcategory();
    }
    public NOTIFY() {
        initComponents();
        strtbtn.hide();
        con= new ConnectDB().Connect();
        getcategory();
    }
    
    
    
    
    
    
     
    public void getcategory(){
        
        try{
            str=con.prepareStatement("select* from `category`");
            rs=str.executeQuery();
            while(rs.next()){
                select.addItem(rs.getString("CATEGORY"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }
    public void QuestionsCHECK(){
         
        int c;
        try {

            str=con.prepareStatement ("SELECT COUNT(*) FROM addquestion WHERE CATEGORY='"+select.getSelectedItem()+"'");
            rs=str.executeQuery();
                    
            if (rs.next()){
                System.out.println(rs.getString("COUNT(*)"));
                if (rs.getInt("COUNT(*)")>=10){
                    if(select.getSelectedItem().equals("NONE")){
                        JOptionPane.showMessageDialog(this,"PLEASE SELECT A CATEGORY FOR QUIZ");
                    }else{
                        this.dispose();
                        new QUIZ(ID1,NAME1,CATEGORY1).setVisible(true);
                    }
                }else{
                    JOptionPane.showMessageDialog(this,"QUESTION ARE NOT COMPLETE IN "+select.getSelectedItem().toString());
                }
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,ex,"CONNECTION ",3);
        }
    
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        select = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        strtbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "INSTRUCTION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Agency FB", 1, 48))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(204, 255, 255));
        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextPane1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jTextPane1.setText("1. Online Quiz will be conducted on MCQ based method.\n2. The duration of the test will be 10 min and there will 10 Question 1 min for each.\n3. There will be Three choices for each question. Only one of these choices is correct.\n4. Start Quiz Button well be Visible after You agree to instruction.\n5. After reading test information click on Start Test.\n6. Read question carefully, tick ONE correct option from A, B, C  and click on Next.\n7. Test will automatically get closed if the duration of the test is over.");
        jTextPane1.setOpaque(false);
        jTextPane1.setSelectionColor(new java.awt.Color(0, 255, 0));
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 970, 320));

        select.setBackground(new java.awt.Color(0, 0, 0,0));
        select.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE" }));
        select.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 390, 70));

        jCheckBox1.setBackground(new java.awt.Color(0, 255, 204));
        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox1.setText("I HAVE READ  ALL THE ABOVE INSTRUCTION.");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 350, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setText("SELECT CATEGORY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 230, 70));

        strtbtn.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        strtbtn.setText("START QUIZ");
        strtbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        strtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strtbtnActionPerformed(evt);
            }
        });
        jPanel1.add(strtbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 260, 60));

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-close-36.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void strtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strtbtnActionPerformed
        // TODO add your handling code here:
       QuestionsCHECK();
    }//GEN-LAST:event_strtbtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()){
            strtbtn.show();
        }else{
            strtbtn.hide();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        
        if(!select.getSelectedItem().equals("NONE")){
            CATEGORY1=select.getSelectedItem().toString();
        }
        
    }//GEN-LAST:event_selectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        studentmain.Kye=0;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NOTIFY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NOTIFY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NOTIFY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NOTIFY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NOTIFY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JButton strtbtn;
    // End of variables declaration//GEN-END:variables
}
// software made by MUHAMMAD UZAIR 👦👍
//923099891084 WHATSAPP
//THANK YOU.❤😍😘😊💕👍✨✨✨✨✨✨✨

