/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FILES;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.*;
import javax.swing.JOptionPane;


/**
 *
 * @author User1
 */
public class REGISTER extends javax.swing.JFrame {

    /**
     * Creates new form REGISTER
     */
    static int kye1=0;
    Connection con ;
    PreparedStatement str;
    ResultSet rs;
    String s="";
//    public REGISTER() {
//        initComponents();
//        ConnectDB c = new ConnectDB();
//        con = c.Connect();
//        
//    }
    public REGISTER(int k) {
        initComponents();
        ConnectDB c = new ConnectDB();
        con = c.Connect();
        kye1=k;
        if (kye1==1){
            jButton4.hide();
        }else{
            jButton4.show(true);
        }
        System.out.println(kye1);
    }

    
    
    
    
    
    public void submit(){
       
        if ( NAME.getText().equals("") || AGE.getText().equals("") || LASTNAME.getText().equals("")|| CNIC.getText().equals("")
                || USERNAME.getText().equals("") || PHONE.getText().equals("") || !CPASSWORD.getText().equals(PASSWORD.getText())|| PASSWORD.getText().equals("")||EMAIL.getText().equals(""))
        {  
            JOptionPane.showMessageDialog(this,"INCOMPLETE ENTERY");
        }
        else
        {

                try{
                    str=con.prepareStatement("SELECT * FROM `STUDENTDETAIL` WHERE USERNAME=?");

                    str.setString(1,USERNAME.getText());
                    rs=str.executeQuery();
                    if (rs.next())
                    {
                        JOptionPane.showMessageDialog(this,"This USERNAME Already In use ","change username",1);
                    }
                    else
                    {
                        str=con.prepareStatement("INSERT INTO `STUDENTDETAIL`( `NAME`, `LASTNAME`, `USERNAME`,`AGE`, `PHONE`, `email`, `cnic`, `gender`,`password`, `img`)VALUES(?,?,?,?,?,?,?,?,?,?)");
                        str.setString(1, NAME.getText());
                        str.setString(2, LASTNAME.getText());
                        str.setString(3, USERNAME.getText());
                        str.setString(4, AGE.getText());
                        str.setString(5, PHONE.getText());
                        str.setString(6, EMAIL.getText());
                        str.setString(7, CNIC.getText());
                        str.setString(8, GENDER.getSelectedItem().toString());
                        str.setString(9, PASSWORD.getText());
                        InputStream Img =new FileInputStream(new File(s));
                        str.setBlob(10, Img);
                        str.executeUpdate();
                        JOptionPane.showMessageDialog(this,"DATA SAVED","SUCCESS",1);
                    }
                        clear();
                    }
                catch(Exception e)
                {
                        JOptionPane.showMessageDialog(this,e,"DATABASE ERROR",3);
                }
        }
    }
    
    public void Message(JTextField tf,JLabel jl)
    {
        if(tf.getText().equals("")||tf.getText().equals(" ")|| tf.getText() == null){
            jl.setText("*Field Required");
            
        }else{
            jl.setText("");
        }
        
    } 
    
    
    public void clear(){
        
        NAME.setText("");
        LASTNAME.setText("");
        USERNAME.setText("");
        AGE.setText("");
        EMAIL.setText("");
        GENDER.setSelectedIndex(0);
        GENDER.setSelectedItem("");
        PHONE.setText("");
        PASSWORD.setText("");
        CPASSWORD.setText("");
        img.setIcon(null);
        pt.setText("");
        CNIC.setText("");
        s="";
    }
    
    
    
    public void nospace(JTextField JF){
        
        KeyStroke ks= KeyStroke.getKeyStroke(Character.valueOf(' '), 0);
        JF.getInputMap(JComponent.WHEN_FOCUSED).put(ks,"none");
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UNmessage = new javax.swing.JLabel();
        Nmessage = new javax.swing.JLabel();
        FNmessage = new javax.swing.JLabel();
        Amessage = new javax.swing.JLabel();
        Emessage = new javax.swing.JLabel();
        Pmessage = new javax.swing.JLabel();
        P1message = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NAME = new javax.swing.JTextField();
        USERNAME = new javax.swing.JTextField();
        PHONE = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        LASTNAME = new javax.swing.JTextField();
        AGE = new javax.swing.JTextField();
        CNIC = new javax.swing.JTextField();
        GENDER = new javax.swing.JComboBox<>();
        CPmessage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        pt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        SPassword = new javax.swing.JCheckBox();
        PASSWORD = new javax.swing.JPasswordField();
        CPASSWORD = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "REGISTRATION FORM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Agency FB", 1, 48))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNmessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        UNmessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(UNmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 100, 20));

        Nmessage.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        Nmessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(Nmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 100, 20));

        FNmessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FNmessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(FNmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 110, 20));

        Amessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Amessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(Amessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, 20));

        Emessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Emessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(Emessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 100, 20));

        Pmessage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Pmessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(Pmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, 20));

        P1message.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        P1message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(P1message, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 100, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-close-36.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 40));

        NAME.setBackground(new java.awt.Color(204, 204, 255));
        NAME.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NAME.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*FIRST NAME", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        NAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NAMEFocusLost(evt);
            }
        });
        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });
        jPanel1.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 80));

        USERNAME.setBackground(new java.awt.Color(204, 204, 255));
        USERNAME.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        USERNAME.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*USERNAME", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        USERNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                USERNAMEFocusLost(evt);
            }
        });
        USERNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                USERNAMEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                USERNAMEKeyReleased(evt);
            }
        });
        jPanel1.add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 280, 80));

        PHONE.setBackground(new java.awt.Color(204, 204, 255));
        PHONE.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        PHONE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*PHONE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        PHONE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PHONEFocusLost(evt);
            }
        });
        PHONE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PHONEKeyPressed(evt);
            }
        });
        jPanel1.add(PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 280, 80));

        EMAIL.setBackground(new java.awt.Color(204, 204, 255));
        EMAIL.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EMAIL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*EMAIL", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        EMAIL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EMAILFocusLost(evt);
            }
        });
        EMAIL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EMAILKeyPressed(evt);
            }
        });
        jPanel1.add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 280, 80));

        LASTNAME.setBackground(new java.awt.Color(204, 204, 255));
        LASTNAME.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        LASTNAME.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*LAST NAME", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        LASTNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LASTNAMEFocusLost(evt);
            }
        });
        jPanel1.add(LASTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 280, 80));

        AGE.setBackground(new java.awt.Color(204, 204, 255));
        AGE.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        AGE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*AGE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24))); // NOI18N
        AGE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AGEFocusLost(evt);
            }
        });
        AGE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AGEKeyPressed(evt);
            }
        });
        jPanel1.add(AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 280, 80));

        CNIC.setBackground(new java.awt.Color(204, 204, 255));
        CNIC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        CNIC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*STUDENT ID #", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        CNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CNICKeyPressed(evt);
            }
        });
        jPanel1.add(CNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 280, 80));

        GENDER.setBackground(new java.awt.Color(0, 0, 0,0));
        GENDER.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "MALE", "FEMALE", "PRIVATE" }));
        GENDER.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "GENDER", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel1.add(GENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 280, 80));

        CPmessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CPmessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(CPmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 210, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-submit-progress-36.png"))); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 210, 60));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-customer-100.png"))); // NOI18N
        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopPane1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 220));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 220, 220));

        pt.setEditable(false);
        pt.setBackground(new java.awt.Color(255, 255, 255));
        pt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(pt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 160, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton3.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jButton3.setText("browse");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 60, 40));

        SPassword.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        SPassword.setText("Show Password");
        SPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(SPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, 30));

        PASSWORD.setBackground(new java.awt.Color(204, 204, 255));
        PASSWORD.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        PASSWORD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "*PASSWORD", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        PASSWORD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PASSWORDFocusLost(evt);
            }
        });
        PASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PASSWORDKeyPressed(evt);
            }
        });
        jPanel1.add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 280, 80));

        CPASSWORD.setBackground(new java.awt.Color(204, 204, 255));
        CPASSWORD.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        CPASSWORD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "CONFIRM PASSWORD", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        CPASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CPASSWORDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CPASSWORDKeyReleased(evt);
            }
        });
        jPanel1.add(CPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 280, 80));

        jButton4.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-back-36.png"))); // NOI18N
        jButton4.setText("BACK TO LOGIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, 230, 50));

        jLabel1.setFont(new java.awt.Font("Alvi Nastaleeq", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-info-24.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 80, 30, 30));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-info-24.png"))); // NOI18N
        jLabel2.setText("REGISTERED INFORMATION CAN'T BE CHANGE.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 30));

        jLabel3.setFont(new java.awt.Font("Alvi Nastaleeq", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("\"*\" والے نشان کے ساتھ ٹیکسٹ فیلڈز لازمی درکار ہیں۔");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 360, 30));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-info-24.png"))); // NOI18N
        jLabel4.setText("Text fields marked with a \"*\" are required.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 390, 30));

        jLabel5.setFont(new java.awt.Font("Alvi Nastaleeq", 0, 18)); // NOI18N
        jLabel5.setText("براہ کرم تمام معلومات کو درست طریقے سے پُر کرنے کو یقینی بنائیں");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 430, 30));

        jLabel6.setFont(new java.awt.Font("Alvi Nastaleeq", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-info-24.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, 30, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/SC-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 480, 510));

        jButton5.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-clear-50.png"))); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 130, 60));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-info-24.png"))); // NOI18N
        jLabel8.setText("Please make sure to Fill All the information correctly.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 400, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MAINADMIN.kye=0;
        
        this.dispose();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc =new JFileChooser();
        fc.showOpenDialog(this);
        File f = fc.getSelectedFile();
        String path = f.getAbsolutePath();
        ImageIcon i = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(220, 220, Image.SCALE_DEFAULT));
        img.setIcon(i);
        s=path;
        pt.setText(s);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void SPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPasswordActionPerformed
        // TODO add your handling code here:
        if(SPassword.isSelected()){
          PASSWORD.setEchoChar((char)0); 
          CPASSWORD.setEchoChar((char)0); 
        }else{
          PASSWORD.setEchoChar('*'); 
          CPASSWORD.setEchoChar('*');
        }
    }//GEN-LAST:event_SPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        submit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CPASSWORDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPASSWORDKeyReleased
        // TODO add your handling code here:
        if(!CPASSWORD.getText().equals(PASSWORD.getText())|| CPASSWORD.getText().equals("")){
            CPmessage.setForeground(Color.red);
            CPmessage.setText("*Password Doesn't Match");
        }else{
            CPmessage.setForeground(Color.blue);
            CPmessage.setText("*Password Match");
        }
        
    }//GEN-LAST:event_CPASSWORDKeyReleased

    private void NAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NAMEFocusLost
        // TODO add your handling code here:
        Message(NAME,Nmessage);
    }//GEN-LAST:event_NAMEFocusLost

    private void LASTNAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LASTNAMEFocusLost
        // TODO add your handling code here:
       Message(LASTNAME,FNmessage);
    }//GEN-LAST:event_LASTNAMEFocusLost

    private void USERNAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USERNAMEFocusLost
        // TODO add your handling code here:
        Message(USERNAME,UNmessage);
    }//GEN-LAST:event_USERNAMEFocusLost

    private void PHONEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PHONEFocusLost
        // TODO add your handling code here:
        Message(PHONE,Pmessage);
    }//GEN-LAST:event_PHONEFocusLost

    private void EMAILFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EMAILFocusLost
        // TODO add your handling code here:
        Message(EMAIL,Emessage);
    }//GEN-LAST:event_EMAILFocusLost

    private void PASSWORDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PASSWORDFocusLost
        // TODO add your handling code here:
        Message(PASSWORD,P1message);
    }//GEN-LAST:event_PASSWORDFocusLost

    private void AGEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AGEFocusLost
        // TODO add your handling code here:
        Message(AGE,Amessage);
    }//GEN-LAST:event_AGEFocusLost

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(new java.awt.Color(0, 0, 0,0));
    }//GEN-LAST:event_jButton2MouseExited

    private void USERNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERNAMEKeyReleased
        // TODO add your handling code here:
        try{
                    str=con.prepareStatement("SELECT username FROM `STUDENTDETAIL` WHERE USERNAME=?");
                    str.setString(1,USERNAME.getText());
                    rs=str.executeQuery();
                    if (rs.next()){
                        UNmessage.setText("This USERNAME Already In use ");
                        USERNAME.setText("");
                    }else{
                        UNmessage.setText("");
                    }
        }catch(Exception e){
            System.out.println(e);
        }
        
        
        
        
    }//GEN-LAST:event_USERNAMEKeyReleased

    private void USERNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERNAMEKeyPressed
        // TODO add your handling code here:
        
        
        nospace(USERNAME);
    }//GEN-LAST:event_USERNAMEKeyPressed

    private void CNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CNICKeyPressed
        // TODO add your handling code here:
        
        nospace(CNIC);
    }//GEN-LAST:event_CNICKeyPressed

    private void EMAILKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EMAILKeyPressed
        // TODO add your handling code here:
        
        nospace(EMAIL);
    }//GEN-LAST:event_EMAILKeyPressed

    private void PASSWORDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PASSWORDKeyPressed
        // TODO add your handling code here:
         
        nospace(PASSWORD);
    }//GEN-LAST:event_PASSWORDKeyPressed

    private void CPASSWORDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPASSWORDKeyPressed
        // TODO add your handling code here:
         
        nospace(CPASSWORD);
    }//GEN-LAST:event_CPASSWORDKeyPressed

    private void AGEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AGEKeyPressed
        // TODO add your handling code here:
        
        nospace(AGE);
    }//GEN-LAST:event_AGEKeyPressed

    private void PHONEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PHONEKeyPressed
        // TODO add your handling code here:
        nospace(PHONE);
    }//GEN-LAST:event_PHONEKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTER(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGE;
    private javax.swing.JLabel Amessage;
    private javax.swing.JTextField CNIC;
    private javax.swing.JPasswordField CPASSWORD;
    private javax.swing.JLabel CPmessage;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JLabel Emessage;
    private javax.swing.JLabel FNmessage;
    private javax.swing.JComboBox<String> GENDER;
    private javax.swing.JTextField LASTNAME;
    private javax.swing.JTextField NAME;
    private javax.swing.JLabel Nmessage;
    private javax.swing.JLabel P1message;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JTextField PHONE;
    private javax.swing.JLabel Pmessage;
    private javax.swing.JCheckBox SPassword;
    private javax.swing.JLabel UNmessage;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pt;
    // End of variables declaration//GEN-END:variables
}
