//software made by MUHAMMAD UZAIR 
//923099891084 WHATSAPP
//THANK YOU.❤😍😘😊💕👍✨✨✨✨✨✨✨



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FILES;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class studentmain extends javax.swing.JFrame {

    /**
     * Creates new form studentmain
     */
    Connection con ;
    PreparedStatement str;
    ResultSet rs;

    public static int Kye;
    
    
    public String USERNAME;
    public String PASSWORD;
     // this constructor will be used if this form opend after login 
    public studentmain(String u,String p) {
        this.USERNAME=u;
        this.PASSWORD=p;      
        initComponents();
        ConnectDB c=new ConnectDB();
        con=c.Connect();
        getdata(USERNAME);
    }

    // this constructor will be used if this form open directly from IDE just for testing purpose 
    
     public studentmain() {
        initComponents();
        ConnectDB c=new ConnectDB();
        con=c.Connect();
        getdata(USERNAME);
    }
    
    
    
    
    
    ///////////////////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////
    public String getUSERNAME() {
        return USERNAME;
    }

    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME;
    }

    public String getPASSWORD() {
        return PASSWORD;
    }

    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD;
    }
    
    
    
    /////////////////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////       GETTER AND SETTER
    
    
    
    
    public void getdata(String U){
    
        
        int c;
        try {
            str=con.prepareStatement ("SELECT * FROM studentdetail WHERE USERNAME='"+U+"'");
            rs=str.executeQuery();
                    if (rs.next()){
                    String add=(rs.getString("ID"));
                    ID.setText(add);
                    String add1=(rs.getString("NAME"));
                    NAME.setText(add1);
                    String add2=(rs.getString("USERNAME"));
                    USERNAME2.setText(add2);
                    String add3=(rs.getString("EMAIL"));
                    EMAIL.setText(add3);
                    String add4=(rs.getString("PHONE"));
                    PHONE.setText(add4);
                    byte[] Img = rs.getBytes("img");
                        //Resize The ImageIcon
                        ImageIcon image = new ImageIcon(Img);
                        Image im = image.getImage();
                        Image myImg = im.getScaledInstance(220,220,Image.SCALE_SMOOTH);
                        ImageIcon newImage = new ImageIcon(myImg);
                        img.setIcon(newImage);
                    
                    }else {
                        JOptionPane.showMessageDialog(this,"NO DATA AVALIBLE ⚠⚠","NO DATA",2);
                    }
           
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex,"CONNECTION ",3);
        }
    }
    
    
    
//    public void unlock(){
//        quiz.show();
//        view.show();
//        lead.show();
//        
//    }    
//     public void lock(){
//        quiz.hide();
//        view.hide();
//        lead.hide();
//        
//    }    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lead = new javax.swing.JButton();
        quiz = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lead1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        ID1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        USERNAME2 = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        PHONE = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "STUDENT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Agency FB", 1, 48))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "ACTIONS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Agency FB", 1, 48))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lead.setBackground(new java.awt.Color(0, 0, 0,0));
        lead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/high-score-removebg-preview.png"))); // NOI18N
        lead.setBorder(new javax.swing.border.MatteBorder(null));
        lead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadActionPerformed(evt);
            }
        });
        jPanel4.add(lead, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 150, 110));

        quiz.setBackground(new java.awt.Color(0, 0, 0,0));
        quiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/choose-removebg-preview.png"))); // NOI18N
        quiz.setBorder(new javax.swing.border.MatteBorder(null));
        quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizActionPerformed(evt);
            }
        });
        jPanel4.add(quiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 150, 110));

        view.setBackground(new java.awt.Color(0, 0, 0,0));
        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/analysis-removebg-preview.png"))); // NOI18N
        view.setBorder(new javax.swing.border.MatteBorder(null));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel4.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, 110));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SETTING");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 150, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TAKE QUIZ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VIEW YOUR INFO");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 170, 150, -1));

        lead1.setBackground(new java.awt.Color(0, 0, 0,0));
        lead1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-gear-100.png"))); // NOI18N
        lead1.setBorder(new javax.swing.border.MatteBorder(null));
        lead1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lead1ActionPerformed(evt);
            }
        });
        jPanel4.add(lead1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 150, 110));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("~ON THE TOP~");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 150, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 740, 210));

        jButton4.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-close-36.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 10, 50, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FILES/pics/icons8-logout-100.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, -1, 100));

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "INFO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Agency FB", 1, 48))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ID.setText("NONE");
        jPanel9.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 50));

        ID1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        ID1.setText("ID#");
        jPanel9.add(ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 50));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jDesktopPane1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 220));

        jPanel9.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 220));

        USERNAME2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        USERNAME2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USERNAME2.setText("NONE");
        USERNAME2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "USERANAME", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        USERNAME2.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel9.add(USERNAME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 400, 70));

        NAME.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NAME.setText("NONE");
        NAME.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "NAME", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        NAME.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel9.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 400, 70));

        PHONE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PHONE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PHONE.setText("NONE");
        PHONE.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "PHONE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        PHONE.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel9.add(PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 460, 70));

        EMAIL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EMAIL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EMAIL.setText("NONE");
        EMAIL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "EMAIL", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        EMAIL.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel9.add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 460, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 880, 2));
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1130, 2));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1130, 2));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 2, 240));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1160, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(Kye==0){
        System.exit(0);
        }else{
            MAINADMIN.showmasseg();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void leadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadActionPerformed
        // TODO add your handling code here:
         if (Kye==0){
            new Leaderboard().setVisible(true);
            Kye=1;
         }else{
             MAINADMIN.showmasseg();
         }
            
    }//GEN-LAST:event_leadActionPerformed

    private void quizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizActionPerformed
        // TODO add your handling code here:
        if (Kye==0){
            NOTIFY n = new NOTIFY(ID.getText(),NAME.getText(),USERNAME2.getText());
            n.setVisible(true);
            Kye = 1;
        }else {
           MAINADMIN.showmasseg();
        }
    }//GEN-LAST:event_quizActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (Kye==0){
            this.dispose();
            login l = new login();
            l.setVisible(true);
            
        }else{
            MAINADMIN.showmasseg();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
         if (Kye==0){ 
             new viewresult(ID.getText()).setVisible(true);
             Kye=1;
         }else{
             MAINADMIN.showmasseg();
         }
    }//GEN-LAST:event_viewActionPerformed

    private void lead1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lead1ActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(this, "Action Not AVALIBAL");
         if (Kye==0){ 
             new STUsetting(ID.getText()).setVisible(true);
             Kye=1;
         }else{
             MAINADMIN.showmasseg();
         }
    }//GEN-LAST:event_lead1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                studentmain s = new studentmain();
                s.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PHONE;
    private javax.swing.JLabel USERNAME2;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton lead;
    private javax.swing.JButton lead1;
    private javax.swing.JButton quiz;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
